name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          #### Paths
          app_location: "/"          # root of the repo
          api_location: ""            # no API
          output_location: "/"        # static files are in root
        env:
          #### Optional environment variables
          #### CUSTOM_DOMAIN: ""      # set later in Azure portal

